# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(497, 477)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TemperCtl = QtWidgets.QGroupBox(self.centralwidget)
        self.TemperCtl.setGeometry(QtCore.QRect(10, 10, 251, 91))
        self.TemperCtl.setObjectName("TemperCtl")
        self.labelCol = QtWidgets.QLabel(self.TemperCtl)
        self.labelCol.setGeometry(QtCore.QRect(30, 30, 54, 12))
        self.labelCol.setObjectName("labelCol")
        self.labelSam = QtWidgets.QLabel(self.TemperCtl)
        self.labelSam.setGeometry(QtCore.QRect(30, 60, 54, 12))
        self.labelSam.setObjectName("labelSam")
        self.comboBoxSTem_2 = QtWidgets.QComboBox(self.TemperCtl)
        self.comboBoxSTem_2.setGeometry(QtCore.QRect(90, 20, 69, 22))
        self.comboBoxSTem_2.setObjectName("comboBoxSTem_2")
        self.comboBoxTem_3 = QtWidgets.QComboBox(self.TemperCtl)
        self.comboBoxTem_3.setGeometry(QtCore.QRect(90, 50, 69, 22))
        self.comboBoxTem_3.setObjectName("comboBoxTem_3")
        self.PDAdetector = QtWidgets.QGroupBox(self.centralwidget)
        self.PDAdetector.setGeometry(QtCore.QRect(10, 110, 251, 161))
        self.PDAdetector.setObjectName("PDAdetector")
        self.ifDetector = QtWidgets.QCheckBox(self.PDAdetector)
        self.ifDetector.setGeometry(QtCore.QRect(30, 20, 81, 16))
        self.ifDetector.setObjectName("ifDetector")
        self.srSeq = QtWidgets.QLabel(self.PDAdetector)
        self.srSeq.setGeometry(QtCore.QRect(30, 40, 54, 21))
        self.srSeq.setObjectName("srSeq")
        self.if3D = QtWidgets.QCheckBox(self.PDAdetector)
        self.if3D.setGeometry(QtCore.QRect(30, 70, 91, 16))
        self.if3D.setObjectName("if3D")
        self.labelLen = QtWidgets.QLabel(self.PDAdetector)
        self.labelLen.setGeometry(QtCore.QRect(30, 100, 201, 16))
        self.labelLen.setObjectName("labelLen")
        self.lineRangeL = QtWidgets.QLineEdit(self.PDAdetector)
        self.lineRangeL.setGeometry(QtCore.QRect(80, 100, 51, 20))
        self.lineRangeL.setObjectName("lineRangeL")
        self.lineRangeR = QtWidgets.QLineEdit(self.PDAdetector)
        self.lineRangeR.setGeometry(QtCore.QRect(160, 100, 51, 20))
        self.lineRangeR.setObjectName("lineRangeR")
        self.labelRes = QtWidgets.QLabel(self.PDAdetector)
        self.labelRes.setGeometry(QtCore.QRect(30, 130, 121, 21))
        self.labelRes.setObjectName("labelRes")
        self.comboBoxSam = QtWidgets.QComboBox(self.PDAdetector)
        self.comboBoxSam.setGeometry(QtCore.QRect(80, 40, 69, 22))
        self.comboBoxSam.setObjectName("comboBoxSam")
        self.comboBoxRes = QtWidgets.QComboBox(self.PDAdetector)
        self.comboBoxRes.setGeometry(QtCore.QRect(80, 130, 41, 22))
        self.comboBoxRes.setObjectName("comboBoxRes")
        self.SampleCtl = QtWidgets.QGroupBox(self.centralwidget)
        self.SampleCtl.setGeometry(QtCore.QRect(10, 280, 251, 151))
        self.SampleCtl.setObjectName("SampleCtl")
        self.lineLowPSI = QtWidgets.QLineEdit(self.SampleCtl)
        self.lineLowPSI.setGeometry(QtCore.QRect(100, 30, 113, 20))
        self.lineLowPSI.setObjectName("lineLowPSI")
        self.labelLowPSI = QtWidgets.QLabel(self.SampleCtl)
        self.labelLowPSI.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.labelLowPSI.setObjectName("labelLowPSI")
        self.labelSheet = QtWidgets.QLabel(self.SampleCtl)
        self.labelSheet.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.labelSheet.setObjectName("labelSheet")
        self.lineSheet = QtWidgets.QLineEdit(self.SampleCtl)
        self.lineSheet.setGeometry(QtCore.QRect(20, 120, 151, 20))
        self.lineSheet.setObjectName("lineSheet")
        self.LabelPath = QtWidgets.QPushButton(self.SampleCtl)
        self.LabelPath.setGeometry(QtCore.QRect(180, 120, 41, 21))
        self.LabelPath.setObjectName("LabelPath")
        self.lineHighPSI = QtWidgets.QLineEdit(self.SampleCtl)
        self.lineHighPSI.setGeometry(QtCore.QRect(100, 60, 113, 20))
        self.lineHighPSI.setObjectName("lineHighPSI")
        self.labelHighPSI = QtWidgets.QLabel(self.SampleCtl)
        self.labelHighPSI.setGeometry(QtCore.QRect(20, 60, 81, 16))
        self.labelHighPSI.setObjectName("labelHighPSI")
        self.MonitorCtl = QtWidgets.QGroupBox(self.centralwidget)
        self.MonitorCtl.setGeometry(QtCore.QRect(270, 10, 221, 361))
        self.MonitorCtl.setObjectName("MonitorCtl")
        self.ifTemperCtl = QtWidgets.QCheckBox(self.MonitorCtl)
        self.ifTemperCtl.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.ifTemperCtl.setObjectName("ifTemperCtl")
        self.settingWords = QtWidgets.QLabel(self.MonitorCtl)
        self.settingWords.setGeometry(QtCore.QRect(10, 50, 151, 16))
        self.settingWords.setObjectName("settingWords")
        self.temperSetSam = QtWidgets.QLineEdit(self.MonitorCtl)
        self.temperSetSam.setGeometry(QtCore.QRect(160, 50, 51, 20))
        self.temperSetSam.setObjectName("temperSetSam")
        self.ifPressureCtl = QtWidgets.QCheckBox(self.MonitorCtl)
        self.ifPressureCtl.setGeometry(QtCore.QRect(10, 110, 101, 21))
        self.ifPressureCtl.setObjectName("ifPressureCtl")
        self.settingWords2 = QtWidgets.QLabel(self.MonitorCtl)
        self.settingWords2.setGeometry(QtCore.QRect(10, 140, 151, 16))
        self.settingWords2.setObjectName("settingWords2")
        self.pressureSet = QtWidgets.QLineEdit(self.MonitorCtl)
        self.pressureSet.setGeometry(QtCore.QRect(140, 140, 61, 20))
        self.pressureSet.setObjectName("pressureSet")
        self.Start = QtWidgets.QPushButton(self.MonitorCtl)
        self.Start.setGeometry(QtCore.QRect(10, 330, 81, 23))
        self.Start.setObjectName("Start")
        self.Stop = QtWidgets.QPushButton(self.MonitorCtl)
        self.Stop.setGeometry(QtCore.QRect(110, 330, 81, 23))
        self.Stop.setObjectName("Stop")
        self.titleTemperStatus = QtWidgets.QLabel(self.MonitorCtl)
        self.titleTemperStatus.setGeometry(QtCore.QRect(10, 170, 151, 16))
        self.titleTemperStatus.setObjectName("titleTemperStatus")
        self.valueTempNowSam = QtWidgets.QLabel(self.MonitorCtl)
        self.valueTempNowSam.setGeometry(QtCore.QRect(30, 190, 151, 16))
        self.valueTempNowSam.setObjectName("valueTempNowSam")
        self.titlePressureStatus = QtWidgets.QLabel(self.MonitorCtl)
        self.titlePressureStatus.setGeometry(QtCore.QRect(10, 270, 151, 16))
        self.titlePressureStatus.setObjectName("titlePressureStatus")
        self.valuePressureNow = QtWidgets.QLabel(self.MonitorCtl)
        self.valuePressureNow.setGeometry(QtCore.QRect(30, 300, 151, 16))
        self.valuePressureNow.setObjectName("valuePressureNow")
        self.temperSetCol = QtWidgets.QLineEdit(self.MonitorCtl)
        self.temperSetCol.setGeometry(QtCore.QRect(160, 80, 51, 20))
        self.temperSetCol.setObjectName("temperSetCol")
        self.settingWords3 = QtWidgets.QLabel(self.MonitorCtl)
        self.settingWords3.setGeometry(QtCore.QRect(10, 80, 151, 16))
        self.settingWords3.setObjectName("settingWords3")
        self.titleTemperStatusCol = QtWidgets.QLabel(self.MonitorCtl)
        self.titleTemperStatusCol.setGeometry(QtCore.QRect(10, 220, 151, 16))
        self.titleTemperStatusCol.setObjectName("titleTemperStatusCol")
        self.valueTempNowCol = QtWidgets.QLabel(self.MonitorCtl)
        self.valueTempNowCol.setGeometry(QtCore.QRect(30, 240, 151, 16))
        self.valueTempNowCol.setObjectName("valueTempNowCol")
        self.StartLeft = QtWidgets.QPushButton(self.centralwidget)
        self.StartLeft.setGeometry(QtCore.QRect(270, 380, 221, 21))
        self.StartLeft.setObjectName("StartLeft")
        self.ConfigCtl = QtWidgets.QPushButton(self.centralwidget)
        self.ConfigCtl.setGeometry(QtCore.QRect(270, 410, 221, 21))
        self.ConfigCtl.setObjectName("ConfigCtl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Acquity Bat"))
        self.TemperCtl.setTitle(_translate("MainWindow", "温度控制"))
        self.labelCol.setText(_translate("MainWindow", "色谱柱温"))
        self.labelSam.setText(_translate("MainWindow", "进样温度"))
        self.PDAdetector.setTitle(_translate("MainWindow", "PDA eλ检测器"))
        self.ifDetector.setText(_translate("MainWindow", "启用检测器"))
        self.srSeq.setText(_translate("MainWindow", "采样率/s"))
        self.if3D.setText(_translate("MainWindow", "启用3D数据"))
        self.labelLen.setText(_translate("MainWindow", "波长范围         nm至          nm"))
        self.labelRes.setText(_translate("MainWindow", "采样间隔        nm"))
        self.SampleCtl.setTitle(_translate("MainWindow", "进样控制"))
        self.labelLowPSI.setText(_translate("MainWindow", "最低柱压(psi)"))
        self.labelSheet.setText(_translate("MainWindow", "进样控制表格"))
        self.LabelPath.setText(_translate("MainWindow", "..."))
        self.labelHighPSI.setText(_translate("MainWindow", "最高柱压(psi)"))
        self.MonitorCtl.setTitle(_translate("MainWindow", "监控设置"))
        self.ifTemperCtl.setText(_translate("MainWindow", "启用温度监控"))
        self.settingWords.setText(_translate("MainWindow", "样品超过该温度波动时报警"))
        self.ifPressureCtl.setText(_translate("MainWindow", "启用柱压监控"))
        self.settingWords2.setText(_translate("MainWindow", "超过该压力时报警"))
        self.Start.setText(_translate("MainWindow", "开始捕捉"))
        self.Stop.setText(_translate("MainWindow", "终止"))
        self.titleTemperStatus.setText(_translate("MainWindow", "当前样品温度状态"))
        self.valueTempNowSam.setText(_translate("MainWindow", "---"))
        self.titlePressureStatus.setText(_translate("MainWindow", "当前柱压状态"))
        self.valuePressureNow.setText(_translate("MainWindow", "---"))
        self.settingWords3.setText(_translate("MainWindow", "柱中超过该温度波动时报警"))
        self.titleTemperStatusCol.setText(_translate("MainWindow", "当前柱中温度状态"))
        self.valueTempNowCol.setText(_translate("MainWindow", "---"))
        self.StartLeft.setText(_translate("MainWindow", "开始填写"))
        self.ConfigCtl.setText(_translate("MainWindow", "配置文件调整"))